# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Actor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Actor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x41\x63tor.proto\x12\x12mq.proto.lua.actor\"\x87\x02\n\x05Table\x12\x37\n\x07\x65ntries\x18\x01 \x03(\x0b\x32&.mq.proto.lua.actor.Table.EntriesEntry\x12/\n\x03\x61rr\x18\x02 \x03(\x0b\x32\".mq.proto.lua.actor.Table.ArrEntry\x1aK\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.mq.proto.lua.actor.Variant:\x02\x38\x01\x1aG\n\x08\x41rrEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.mq.proto.lua.actor.Variant:\x02\x38\x01\"4\n\x06ImVec2\x12\x0e\n\x01x\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x0e\n\x01y\x18\x02 \x01(\x02H\x01\x88\x01\x01\x42\x04\n\x02_xB\x04\n\x02_y\"`\n\x06ImVec4\x12\x0e\n\x01x\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x0e\n\x01y\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x0e\n\x01z\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x0e\n\x01w\x18\x04 \x01(\x02H\x03\x88\x01\x01\x42\x04\n\x02_xB\x04\n\x02_yB\x04\n\x02_zB\x04\n\x02_w\"\xce\x01\n\x07Variant\x12\x10\n\x06number\x18\x01 \x01(\x01H\x00\x12\x11\n\x07\x62oolean\x18\x05 \x01(\x08H\x00\x12\r\n\x03str\x18\x08 \x01(\tH\x00\x12*\n\x05table\x18\n \x01(\x0b\x32\x19.mq.proto.lua.actor.TableH\x00\x12,\n\x06imvec2\x18\x0b \x01(\x0b\x32\x1a.mq.proto.lua.actor.ImVec2H\x00\x12,\n\x06imvec4\x18\x0c \x01(\x0b\x32\x1a.mq.proto.lua.actor.ImVec4H\x00\x42\x07\n\x05valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Actor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TABLE_ENTRIESENTRY']._loaded_options = None
  _globals['_TABLE_ENTRIESENTRY']._serialized_options = b'8\001'
  _globals['_TABLE_ARRENTRY']._loaded_options = None
  _globals['_TABLE_ARRENTRY']._serialized_options = b'8\001'
  _globals['_TABLE']._serialized_start=36
  _globals['_TABLE']._serialized_end=299
  _globals['_TABLE_ENTRIESENTRY']._serialized_start=151
  _globals['_TABLE_ENTRIESENTRY']._serialized_end=226
  _globals['_TABLE_ARRENTRY']._serialized_start=228
  _globals['_TABLE_ARRENTRY']._serialized_end=299
  _globals['_IMVEC2']._serialized_start=301
  _globals['_IMVEC2']._serialized_end=353
  _globals['_IMVEC4']._serialized_start=355
  _globals['_IMVEC4']._serialized_end=451
  _globals['_VARIANT']._serialized_start=454
  _globals['_VARIANT']._serialized_end=660
# @@protoc_insertion_point(module_scope)
