# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Network.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Network.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Routing_pb2 as Routing__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rNetwork.proto\x12\x0fmq.peerpnetwork\x1a\rRouting.proto\"&\n\x08Identity\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\"\x82\x01\n\x06Header\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.mq.peerpnetwork.MessageType\x12\x0e\n\x06length\x18\x02 \x01(\r\x12\x14\n\x07\x61\x64\x64ress\x18\x0b \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04port\x18\x0c \x01(\rH\x01\x88\x01\x01\x42\n\n\x08_addressB\x07\n\x05_port\"\xc4\x01\n\x0eNetworkMessage\x12,\n\x03\x61\x64\x64\x18\x01 \x01(\x0b\x32\x1d.mq.proto.routing.AddIdentityH\x00\x12.\n\x04\x64rop\x18\x02 \x01(\x0b\x32\x1e.mq.proto.routing.DropIdentityH\x00\x12\x36\n\x07request\x18\x03 \x01(\x0b\x32#.mq.proto.routing.RequestIdentitiesH\x00\x12\x10\n\x06routed\x18\n \x01(\x0cH\x00\x42\n\n\x08\x63ontents\")\n\x08\x41nnounce\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r*A\n\x0bMessageType\x12\t\n\x05Route\x10\x00\x12\n\n\x06Leader\x10\x01\x12\r\n\tHandshake\x10\x02\x12\x0c\n\x08Response\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETYPE']._serialized_start=464
  _globals['_MESSAGETYPE']._serialized_end=529
  _globals['_IDENTITY']._serialized_start=49
  _globals['_IDENTITY']._serialized_end=87
  _globals['_HEADER']._serialized_start=90
  _globals['_HEADER']._serialized_end=220
  _globals['_NETWORKMESSAGE']._serialized_start=223
  _globals['_NETWORKMESSAGE']._serialized_end=419
  _globals['_ANNOUNCE']._serialized_start=421
  _globals['_ANNOUNCE']._serialized_end=462
# @@protoc_insertion_point(module_scope)
